### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [fox-it/OpenSSH-Network-Parser#2]
```
$ network-parser -p debian.pcapng -o ./ --proto ssh --popt KEY=keys.json
getrlimit: (1024, 1048576)
Exception in handle_tcp_stream: No module named dissect
```

**Comment by yunzheng** [comment]
Did you install `dissect.cstruct` using `python2` or `python3`? eg: what version of python does your `pip` command use?

**Comment by alwaysreason** [comment]
Thank you for replying!
![image](https://user-images.githubusercontent.com/100110222/211314419-4c39b375-1158-4725-b3d9-89dbd46e80da.png)
i tried all bro

**Comment by alwaysreason** [comment]
I mean i tried all
>`pip2 install dissect`
`sudo pip2 install dissect`
`pip2 install dissect.cstruct`
`sudo pip2 install dissect.cstruct`
`sudo pip2 install dissect-cstruct`
`pip2 install dissect-cstruct`
still no luck 
```
$ pip2 install dissect
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: dissect in /home/ubuntu/.local/lib/python2.7/site-packages (3.2)
Requirement already satisfied: dissect.sql==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.extfs==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.shellitem==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.cim==3.2 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.2)
Requirement already satisfied: dissect.cstruct==3.2 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.2)
Requirement already satisfied: dissect.util==3.2 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.2)
Requirement already satisfied: dissect.target[full]==3.3 in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect) (3.3)
Requirement already satisfied: dissect.volume==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.eventlog==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.xfs==3.1 in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect) (3.1)
Requirement already satisfied: dissect.etl==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.ffs==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.ole==3.1 in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect) (3.1)
Requirement already satisfied: dissect.esedb==3.2 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.2)
Requirement already satisfied: dissect.clfs==1.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (1.1)
Requirement already satisfied: dissect.evidence==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.fat==3.1 in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect) (3.1)
Requirement already satisfied: dissect.regf==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: dissect.hypervisor==3.2 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.2)
Requirement already satisfied: dissect.vmfs==3.1 in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect) (3.1)
Requirement already satisfied: dissect.ntfs==3.1 in /usr/local/lib/python2.7/dist-packages (from dissect) (3.1)
Requirement already satisfied: flow.record~=3.5 in /usr/local/lib/python2.7/dist-packages (from dissect.target[full]==3.3->dissect) (3.5)
Requirement already satisfied: structlog in /usr/local/lib/python2.7/dist-packages (from dissect.target[full]==3.3->dissect) (20.1.0)
Requirement already satisfied: asn1crypto; extra == "full" in /usr/local/lib/python2.7/dist-packages (from dissect.target[full]==3.3->dissect) (1.5.1)
Requirement already satisfied: defusedxml; extra == "full" in /usr/local/lib/python2.7/dist-packages (from dissect.target[full]==3.3->dissect) (0.7.1)
Requirement already satisfied: ipython; extra == "full" in /usr/local/lib/python2.7/dist-packages (from dissect.target[full]==3.3->dissect) (5.10.0)
Requirement already satisfied: pyyaml; extra == "full" in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect.target[full]==3.3->dissect) (5.4.1)
Requirement already satisfied: fusepy; extra == "full" in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect.target[full]==3.3->dissect) (3.0.1)
Requirement already satisfied: zstandard; extra == "full" in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect.target[full]==3.3->dissect) (0.14.1)
Requirement already satisfied: yara-python; extra == "full" in /home/ubuntu/.local/lib/python2.7/site-packages (from dissect.target[full]==3.3->dissect) (4.2.3)
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib/python2.7/dist-packages (from flow.record~=3.5->dissect.target[full]==3.3->dissect) (1.0.4)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from structlog->dissect.target[full]==3.3->dissect) (1.16.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (0.8.1)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (1.0.0)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (44.0.0)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (2.3.7.post1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (4.4.2)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (4.3.3)
Requirement already satisfied: pygments<2.6 in /usr/local/lib/python2.7/dist-packages (from ipython; extra == "full"->dissect.target[full]==3.3->dissect) (2.5.2)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (1.10.0)
Requirement already satisfied: typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (3.10.0.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect; sys_platform != "win32"->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (0.2.5)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.2->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (1.1.10)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.2->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (0.2.0)
Requirement already satisfied: backports.functools-lru-cache>=1.2.1; python_version < "3.2" in /usr/local/lib/python2.7/dist-packages (from wcwidth->prompt-toolkit<2.0.0,>=1.0.4->ipython; extra == "full"->dissect.target[full]==3.3->dissect) (1.6.4)
```

**Comment by yunzheng** [comment]
Looks good, although only `dissect.cstruct` is needed. When you install `dissect` it will install the whole suite which is not needed for this project. Can you share how you installed this project?

Python 2.7 is deprecated so it might become harder to install this project on newer Linux distributions, so if you can live with using a Docker image, the following works:

```shell
$ docker run -it --rm python:2.7 bash

# follwing commands are in the docker image
$ apt update && apt install -y libpcap-dev
$ git clone https://github.com/fox-it/OpenSSH-Network-Parser
$ cd OpenSSH-Network-Parser
$ pip install -e .
$ network-parser --help
usage: network-parser [-h] -p PCAP -o OUTPUT [--dport DPORT] [--sport SPORT]
                      [--src SRC] [--dst DST] [-s] [-u USER] [--stats STATS]
                      [-f FILE_LIMIT] [--startdate STARTDATE] --proto PROTO
                      [-v] [--popt KEY=VALUE]
```

**Comment by alwaysreason** [comment]
Ey sorry this is error
```
Exception when processing frame: (False, <MsgType.SSH_MSG_NEWKEYS: 21>, '\x15'). Exception: 'chacha20-poly1305@openssh.com'
Traceback (most recent call last):
  File "/OpenSSH-Network-Parser/openssh_network_parser/protocols/ssh/protocol.py", line 112, in _parse
    self.process_frame(is_client, frame_type, frame_data)
  File "/OpenSSH-Network-Parser/openssh_network_parser/protocols/ssh/protocol.py", line 93, in process_frame
    stream_state.process_frame(frame_type, frame_data)
  File "/OpenSSH-Network-Parser/openssh_network_parser/protocols/ssh/state.py", line 211, in process_frame
    frame_processor(frame_data)
  File "/OpenSSH-Network-Parser/openssh_network_parser/protocols/ssh/state.py", line 453, in process_new_keys
    enc_keysize, enc_ivsize, enc_blocksize, mac_keysize, mac_hashsize, etm = get_encryption_params(self.enc_algo_sc, self.mac_alg_cs)
  File "/OpenSSH-Network-Parser/openssh_network_parser/protocols/ssh/crypto/encryption.py", line 232, in get_encryption_params
    encryption, cipher_name = _enc_params[enc_alg]
KeyError: 'chacha20-poly1305@openssh.com'

Server stream offset: 0x560
Client stream offset: 0x5c1
Remaining server data: 0x-1eb4
Remaining client data: 0x-150c
```

**Comment by yunzheng** [comment]
This is a different error, looks like chacha20-poly1306 is not supported, but maybe with some modifications it could be supported. Feel free to open another issue for it.

**Comment by alwaysreason** [comment]
Wow. How did you solve it?

**Comment by yunzheng** [comment]
> Wow. How did you solve it?

I did not solve it. Just saying the `KeyError: 'chacha20-poly1305@openssh.com'` is a different error and not related to this issue. It should be a new issue on its own.
